### ISSUE TITLE
printable area > maximum bed mesh area

### ISSUE THREAD

**Issue by chai-md** [GUTENBERG3DP/G0_klipper_config#3]
[gcode_macro BED_MESH_CALIBRATE]で、mesh areaに制限をかけていないのでスライサーが [bed_mesh] mesh_min～mesh_maxの範囲外を指定するとマクロがとまる。

**Comment by ChipCE** [comment]
mesh areaは[bed_mesh]の設定をそのまま受け取ります
<pre>{% set safe_min_x = bedMeshConfig.mesh_min.split(",")[0]|float %}
        {% set safe_min_y = bedMeshConfig.mesh_min.split(",")[1]|float %}
        {% set safe_max_x = bedMeshConfig.mesh_max.split(",")[0]|float %}
        {% set safe_max_y = bedMeshConfig.mesh_max.split(",")[1]|float %}
</pre>
もしスライサーから渡された値+-offsetが範囲外の値になった場合、bed_meshの設定値で上書きします
<pre>{% if area_min_x - mesh_area_offset >=  safe_min_x %}
                {% set area_min_x = area_min_x - mesh_area_offset %}
            {% else %}
                {% set area_min_x = safe_min_x %}
            {% endif %}

            {% if area_min_y - mesh_area_offset >=  safe_min_y %}
                {% set area_min_y = area_min_y - mesh_area_offset %}
            {% else %}
                {% set area_min_y = safe_min_y %}
            {% endif %}

            {% if area_max_x + mesh_area_offset <=  safe_max_x %}
                {% set area_max_x = area_max_x + mesh_area_offset %}
            {% else %}
                {% set area_max_x = safe_max_x %}
            {% endif %}

            {% if area_max_y + mesh_area_offset <=  safe_max_y %}
                {% set area_max_y = area_max_y + mesh_area_offset %}
            {% else %}
                {% set area_max_y = safe_max_y %}
            {% endif %}
</pre>
実際はどの場合にエラーが発生しましたか。

**Comment by chai-md** [comment]
update.shを実行してからは問題ありません。古いコードだったようです。
